name: photo_wct
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7
  - conda-forge::suitesparse
  - conda-forge::scikit-umfpack
  - conda-forge::axel
  - pip:
      - pillow
      - opencv-contrib-python-headless < 5.0.0.0
      - numpy < 2.0.0
      - scipy
      - cupy-cuda11x
